"""empty message

Revision ID: a8d342dcd6c7
Revises: 4b15a55da056
Create Date: 2023-03-14 23:02:47.974444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d342dcd6c7'
down_revision = '4b15a55da056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('seeking_description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('seeking_description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
